import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description:
    'DebtMeltPro Privacy Policy. Understand our client-side architecture, local calculations, data practices, and privacy rights.',
  robots: { index: true, follow: false },
};

const SECTIONS = [
  {
    title: '1. Core Architectural Principle',
    content: `Financial calculator inputs are processed locally in the browser and are not transmitted to DebtMeltPro servers.

When you use our calculators (entering debt balances, interest rates, income, home prices, or contribution amounts), all mathematical models and amortization simulations run entirely within your device's browser engine using client-side JavaScript. DebtMeltPro does not operate user accounts, databases, or backend APIs that collect or store your financial figures.`,
  },
  {
    title: '2. Information We Do Not Collect',
    content: `Because our application is designed for client-side execution, we do not collect:
- Personal financial inputs (debts, loans, credit card balances, salary, mortgage terms)
- User account credentials, passwords, or profile information
- Personal contact lists or payment card details
- Biometric identifiers or sensitive personal categories`,
  },
  {
    title: '3. Local Storage and Functional Preferences',
    content: `We do not use advertising or third-party tracking cookies. We utilize standard browser storage mechanisms solely for functional, client-side UI convenience:

**Functional Local Storage (localStorage):**
- **Theme Preference:** Stores your dark mode or light mode visual preference via standard client-side state.
- **Last Used Tool:** Stores the identifier of the most recently visited calculator so you can quickly resume where you left off.

**Functional Session Storage (sessionStorage):**
- **Error Recovery Guard:** Stores a temporary technical flag to prevent reload loops if a network disruption occurs during script loading.

These items remain strictly on your device and are never transmitted to our servers or third parties. You can clear them at any time through your browser settings.`,
  },
  {
    title: '4. Third-Party Services & Analytics',
    content: `**No Analytics Services:** DebtMeltPro does not use Google Analytics, tracking pixels, session replay tools, or behavioral analytics software.

**No External IP Geolocation:** We do not transmit your IP address to third-party geolocation services. Currency symbols and number formats are derived directly on your device from your browser's language setting (navigator.language).

**Typography:** Fonts (Inter, Playfair Display) are self-hosted and bundled at build time through Next.js. Your browser does not make runtime network requests to Google Fonts servers.`,
  },
  {
    title: '5. Hosting Infrastructure & Data Transmission',
    content: `**Application-Level Services:** There are zero application-level third-party analytics, tracking, or marketing integrations running on this site.

**Hosting & Network Infrastructure:** When you load web pages, standard HTTP/HTTPS request metadata (such as your IP address, requested URL, and user-agent) is transmitted to our hosting provider, Vercel, to deliver web assets.

*Hosting/infrastructure processing details require verification.* Technical server logs generated by edge infrastructure are managed according to the hosting platform's standard operational security and routing procedures.`,
  },
  {
    title: '6. Privacy Rights & Legal Frameworks',
    content: `Depending on your jurisdiction, you may have specific statutory rights regarding any personal data processed in connection with your web requests:

**General Data Protection Regulation (GDPR - EEA / UK):**
- Right to access information regarding data processing
- Right to request erasure of personal data
- Right to restriction of processing or objection
- Right to lodge a complaint with a supervisory authority

**California Consumer Privacy Act (CCPA / CPRA - California):**
- Right to know what personal information is collected
- Right to request deletion of personal information
- Right to non-discrimination for exercising privacy rights
- We do not sell or share personal information for cross-context behavioral advertising.

**Digital Personal Data Protection Act, 2023 (DPDP Act - India):**
- Right to access information regarding processing
- Right to correction, completion, and erasure of personal data
- Right of grievance redressal through our designated Grievance Officer
- Right to nominate an individual to exercise rights in the event of death or incapacity

To submit an inquiry or exercise applicable rights, please contact our support team at support@debtmeltpro.com.`,
  },
  {
    title: '7. Children\'s Privacy',
    content: `DebtMeltPro is designed as a general-audience educational financial calculator suite. In alignment with DPDP Act provisions regarding minors, our services are not intended for individuals under 18 years of age without parental guidance. We do not knowingly solicit or collect personal information from individuals under 18. If you believe such data has been transmitted to our infrastructure, please notify us at support@debtmeltpro.com.`,
  },
  {
    title: '8. Security Safeguards',
    content: `We implement technical controls to safeguard application delivery:
- Strict HTTPS enforcement with HTTP Strict Transport Security (HSTS)
- Hardened Content Security Policy (CSP) restricting script execution and network connections
- Modern X-Frame-Options (DENY) and X-Content-Type-Options (nosniff) headers
- Client-side data isolation ensuring financial calculations remain on your device`,
  },
  {
    title: '9. Grievance Officer & Contact Information',
    content: `In accordance with applicable data protection requirements (including DPDP Act Section 13):

**Grievance Officer:** OWNER INPUT REQUIRED
**Contact Email:** support@debtmeltpro.com
**Response Time:** Within 30 days of receiving a verifiable request

For questions, feedback, or data privacy inquiries, you may contact us at support@debtmeltpro.com.`,
  },
  {
    title: '10. Changes to This Notice',
    content: `We may revise this Privacy Policy periodically to reflect architectural updates or regulatory changes. Any modifications will be posted on this page with an updated effective date. Continued use of DebtMeltPro constitutes acknowledgment of the updated policy.`,
  },
];

export default function PrivacyPolicyPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <h1 className="font-display text-3xl sm:text-4xl font-bold text-slate-900 dark:text-white mb-2">
        Privacy Policy
      </h1>
      <p className="text-slate-500 dark:text-slate-400 mb-8">
        Last Updated: <time dateTime="2026-08-23">August 23, 2026</time> · Effective Date: August 23, 2026
      </p>

      <div className="card p-6 mb-8 border-l-4 border-l-brand-500">
        <h2 className="font-semibold text-slate-900 dark:text-white mb-2">
          Technical Privacy Commitment
        </h2>
        <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
          Financial calculator inputs are processed locally in the browser and are not transmitted to
          DebtMeltPro servers. Your financial figures (debts, balances, income, interest rates) never leave
          your device.
        </p>
      </div>

      <div className="space-y-8">
        {SECTIONS.map(({ title, content }) => (
          <section key={title}>
            <h2 className="font-semibold text-lg text-slate-900 dark:text-white mb-3">{title}</h2>
            <div className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed space-y-3">
              {content.split('\n\n').map((para, i) => (
                <p
                  key={i}
                  dangerouslySetInnerHTML={{
                    __html: para
                      .replace(
                        /\*\*(.*?)\*\*/g,
                        '<strong class="text-slate-800 dark:text-slate-200">$1</strong>'
                      )
                      .replace(/\n/g, '<br />'),
                  }}
                />
              ))}
            </div>
          </section>
        ))}
      </div>
    </div>
  );
}
